### ISSUE TITLE
Local filesystem path feeds do not work — likely unimplemented

### ISSUE THREAD

**Issue by kado-kliewer** [evan-buss/opds-proxy#60]
Hey, I was trying to use opds-proxy to serve a local directory of .epub files and noticed that the path: field appears supported in the config (based on feed/file.go and the LocalFeed struct), but using it results in a 404 when accessing the expected URL.

Example config I used:

``` yaml
port: 9090

feeds:
  - name: "Library"
    url: "lib"
    path: /home/user/media/books

```

Running the server shows no errors, but the /lib route returns a 404, and no feed is registered. Even with valid book files present in the path, the route never appears on the homepage.

It seems like path: support for local filesystem feeds exists in the source, but the feed loader logic doesn’t register FileFeed types properly.

Would love to see this officially implemented (or documented if I’m missing something)! Happy to PR if needed.
